### ISSUE TITLE
testcontainers-on-whales is leaking containers

### ISSUE THREAD

**Issue by tbalzer** [betaboon/testcontainers-on-whales#26]
We are observing that after test abortions/failures sometimes containers are leaked and are not cleaned up after testing.

Investigation ongoing.

**Comment by betaboon** [comment]
this is hopefully resolved with [0.7.0](https://github.com/betaboon/testcontainers-on-whales/releases/tag/0.7.0)

Can you report back if it solves the issues you're observing?

Thanks for reporting

**Comment by tbalzer** [comment]
> this is hopefully resolved with [0.7.0](https://github.com/betaboon/testcontainers-on-whales/releases/tag/0.7.0)
> 
> Can you report back if it solves the issues you're observing?
> 
> Thanks for reporting

Seems solved. Thanks!
